import 'server-only';

import { createHmac, randomBytes } from 'node:crypto';

/**
 * One-time codes: generation and the digest that is stored in their place.
 *
 * A code is 6 decimal digits from the CSPRNG, drawn by rejection sampling so
 * every code is equally likely — a plain modulo would bias the low end. The
 * store keeps only `HMAC-SHA-256(code, pepper)`; the pepper is a server-held
 * secret (`AUTH_OTP_PEPPER`) the database never sees, so a copy of the store
 * alone, without the pepper, answers no code, current or historical. This
 * mirrors `tokens.ts`'s session token exactly, with one addition: a session
 * token is generated by this server and never needs to be reproduced by a
 * human, so it is opaque bytes; a code is typed by a person from an email, so
 * it is short decimal digits instead — the digest, not the shape, is what
 * carries the security property in both cases.
 */

export const OTP_CODE_LENGTH = 6;
export const OTP_LIFETIME_SECONDS = 10 * 60;
export const OTP_MAX_ATTEMPTS = 5;

const CODE_SHAPE = /^[0-9]{6}$/u;
const MODULUS = 10 ** OTP_CODE_LENGTH;
/** The largest multiple of MODULUS that fits a 32-bit unsigned range, for unbiased rejection sampling. */
const CEILING = Math.floor(0x100000000 / MODULUS) * MODULUS;

/** A uniformly random 6-digit code, zero-padded. */
export function generateOtpCode(): string {
  let value: number;
  do {
    value = randomBytes(4).readUInt32BE(0);
  } while (value >= CEILING);
  return String(value % MODULUS).padStart(OTP_CODE_LENGTH, '0');
}

/** True for a value shaped like a code this code issues. Shape only; not validity. */
export function isOtpCodeShaped(value: unknown): value is string {
  return typeof value === 'string' && CODE_SHAPE.test(value);
}

export function hashOtpCode(code: string, pepper: string): string {
  return createHmac('sha256', pepper).update(code, 'utf8').digest('hex');
}
