import type { DataOrigin, DraftStatus, EvidenceState, NamingDecision } from '@cas/contracts';

import {
  DRAFTING_CONTRACT,
  canonicalize,
  draftingContractHash,
  type ClaimConfidence,
  type DraftSection,
  type DraftingContract,
  type VictimSupport,
} from './contract.js';

/**
 * The deterministic drafting pipeline (decision D25).
 *
 * Pure: no database, no network, no environment, no clock, no randomness and
 * no model call. Decision D9 is unresolved, so nothing here is generated by a
 * model and nothing here may be described as AI-generated. What it is, is an
 * assembler: it turns reviewed incidents and their claims into an editable
 * draft, and it refuses to write anything the input does not support.
 *
 * Three rules it will not bend:
 *
 *   1. **No claim without a source.** A claim carrying fewer sources than the
 *      contract requires is not written, and it is reported as omitted rather
 *      than dropped quietly.
 *   2. **No name without the sourcing D4 requires.** A victim is named on a
 *      primary statement or two independent reports, and otherwise the draft
 *      says plainly that a name is being withheld.
 *   3. **Nothing is smoothed away.** A contradicted evidence state and a
 *      withheld name both appear in the draft, because a draft that hides its
 *      own uncertainty is worse than no draft.
 *
 * A later model adapter must consume this same typed input and produce the
 * same provenance sidecar. It may write better sentences; it may not write a
 * claim without a source, name a victim the policy withholds, or drop the
 * evidence state beside a claim.
 */

export interface DraftSource {
  readonly sourceRowId: string;
  /** Publisher name as recorded at import. Never invented. */
  readonly publisher: string;
  readonly url: string;
  readonly publishedAt: string | null;
}

export interface DraftClaim {
  readonly claimId: string;
  /** The factual sentence, supplied by the caller from reviewed material. */
  readonly text: string;
  readonly confidence: ClaimConfidence;
  /** Sources supporting this claim. At least one, or the claim is omitted. */
  readonly sourceRowIds: readonly string[];
  /** Proposed victim name, or null when the claim names none. */
  readonly victimName: string | null;
  readonly victimSupport: VictimSupport;
}

/** How an incident's Graph evidence stands, in the draft's own words. */
export const GRAPH_EVIDENCE_STATES = [
  'absent',
  'observed',
  'corroborating',
  'contradictory',
] as const;
export type GraphEvidenceState = (typeof GRAPH_EVIDENCE_STATES)[number];

export interface DraftIncident {
  readonly incidentId: string;
  readonly clusteringRunId: string;
  readonly batchId: string;
  readonly evidenceRunId: string | null;
  readonly dataOrigin: DataOrigin;
  readonly evidenceState: EvidenceState;
  readonly graphEvidence: GraphEvidenceState;
  /** True when the incident carries a recorded on-chain subject. */
  readonly onChainSubject: boolean;
  readonly headline: string;
  readonly sources: readonly DraftSource[];
  readonly claims: readonly DraftClaim[];
}

export interface DraftRequest {
  readonly draftId: string;
  /** Explicit, validated window. Never inferred: D10 is unresolved. */
  readonly periodStart: string;
  readonly periodEnd: string;
  readonly dataOrigin: DataOrigin;
  readonly incidents: readonly DraftIncident[];
}

/** One line of the provenance sidecar: what a claim rests on. */
export interface ClaimProvenance {
  readonly claimId: string;
  readonly incidentId: string;
  readonly clusteringRunId: string;
  readonly batchId: string;
  readonly evidenceRunId: string | null;
  readonly dataOrigin: DataOrigin;
  readonly evidenceState: EvidenceState;
  readonly graphEvidence: GraphEvidenceState;
  readonly confidence: ClaimConfidence;
  readonly sourceRowIds: readonly string[];
  readonly namingDecision: NamingDecision;
  readonly written: boolean;
  readonly omissionReason: string | null;
}

export interface DraftProvenance {
  readonly draftId: string;
  readonly status: DraftStatus;
  readonly draftingVersion: string;
  readonly contractVersion: string;
  readonly contractHash: string;
  readonly periodStart: string;
  readonly periodEnd: string;
  readonly dataOrigin: DataOrigin;
  readonly claims: readonly ClaimProvenance[];
  readonly counts: {
    readonly incidents: number;
    readonly claimsWritten: number;
    readonly claimsOmitted: number;
    readonly namesWithheld: number;
    readonly contradicted: number;
    readonly cryptoIncidents: number;
  };
}

export interface GeneratedDraft {
  readonly markdown: string;
  readonly sections: Readonly<Record<DraftSection, string>>;
  readonly provenance: DraftProvenance;
}

const EVIDENCE_SENTENCE: Readonly<Record<EvidenceState, string>> = {
  reported_only: 'Reporting only; no on-chain evidence has been accepted for this incident.',
  onchain_observed:
    'Relevant on-chain activity was observed. It does not establish that this attack occurred.',
  corroborated: 'An accepted on-chain signal supports a specific claim below.',
  contradicted: 'Accepted evidence conflicts with a specific claim below. It is unresolved.',
};

const GRAPH_SENTENCE: Readonly<Record<GraphEvidenceState, string>> = {
  absent: 'Graph evidence: none accepted.',
  observed: 'Graph evidence: observed, not corroborating.',
  corroborating: 'Graph evidence: corroborating a named claim.',
  contradictory: 'Graph evidence: contradictory, unresolved.',
};

function applySubstitutions(text: string, contract: DraftingContract): string {
  let out = text;
  for (const [pattern, replacement] of contract.style.substitutions) {
    out = out.split(pattern).join(replacement);
  }
  return out;
}

function limitSentences(text: string, contract: DraftingContract): string {
  const parts = text.split(/(?<=[.!?])\s+/u).filter((part) => part.trim().length > 0);
  const kept = parts.slice(0, contract.style.maximumSentencesPerItem);
  const truncated = kept.length < parts.length;
  return `${kept.join(' ')}${truncated ? ' […]' : ''}`;
}

function namingDecisionOf(claim: DraftClaim, contract: DraftingContract): NamingDecision {
  if (claim.victimName === null) return 'withheld_insufficient_sourcing';
  return contract.naming.permits[claim.victimSupport];
}

/** Replaces a withheld name with the contract's generic description. */
function applyNaming(
  claim: DraftClaim,
  decision: NamingDecision,
  contract: DraftingContract,
): string {
  const text = applySubstitutions(claim.text, contract);
  if (claim.victimName === null) return text;
  if (decision !== 'withheld_insufficient_sourcing') return text;
  return text.split(claim.victimName).join(contract.naming.genericDescription);
}

const STATE_RANK: Readonly<Record<EvidenceState, number>> = {
  contradicted: 0,
  corroborated: 1,
  onchain_observed: 2,
  reported_only: 3,
};

function orderIncidents(
  incidents: readonly DraftIncident[],
  contract: DraftingContract,
): DraftIncident[] {
  return [...incidents].sort((a, b) => {
    for (const key of contract.incidentOrder) {
      if (key === 'evidence_state') {
        const byState = (STATE_RANK[a.evidenceState] ?? 9) - (STATE_RANK[b.evidenceState] ?? 9);
        if (byState !== 0) return byState;
      } else if (key === 'source_count') {
        const bySources = b.sources.length - a.sources.length;
        if (bySources !== 0) return bySources;
      } else {
        const byId = a.incidentId < b.incidentId ? -1 : a.incidentId > b.incidentId ? 1 : 0;
        if (byId !== 0) return byId;
      }
    }
    return 0;
  });
}

interface RenderedIncident {
  readonly markdown: string;
  readonly provenance: readonly ClaimProvenance[];
}

function renderIncident(incident: DraftIncident, contract: DraftingContract): RenderedIncident {
  const lines: string[] = [];
  const provenance: ClaimProvenance[] = [];
  const sourcesById = new Map(incident.sources.map((source) => [source.sourceRowId, source]));

  lines.push(`**${applySubstitutions(incident.headline, contract)}**`);

  const claims = incident.claims.slice(0, contract.bounds.maximumClaimsPerIncident);
  let withheldHere = false;
  for (const claim of claims) {
    const decision = namingDecisionOf(claim, contract);
    const enough = claim.sourceRowIds.length >= contract.minimumSourcesPerClaim;
    const record: ClaimProvenance = {
      claimId: claim.claimId,
      incidentId: incident.incidentId,
      clusteringRunId: incident.clusteringRunId,
      batchId: incident.batchId,
      evidenceRunId: incident.evidenceRunId,
      dataOrigin: incident.dataOrigin,
      evidenceState: incident.evidenceState,
      graphEvidence: incident.graphEvidence,
      confidence: claim.confidence,
      sourceRowIds: [...claim.sourceRowIds].sort(),
      namingDecision: decision,
      written: enough,
      omissionReason: enough ? null : 'claim_without_source',
    };
    provenance.push(record);
    if (!enough) continue;
    if (decision === 'withheld_insufficient_sourcing' && claim.victimName !== null) {
      withheldHere = true;
    }
    const phrase = contract.style.confidencePhrases[claim.confidence];
    const body = limitSentences(applyNaming(claim, decision, contract), contract);
    lines.push(`${phrase.charAt(0).toUpperCase()}${phrase.slice(1)}: ${body}`);
  }

  lines.push(EVIDENCE_SENTENCE[incident.evidenceState]);
  lines.push(GRAPH_SENTENCE[incident.graphEvidence]);
  if (withheldHere && contract.naming.discloseWithholding) {
    lines.push(
      'A name is withheld here: the sourcing does not meet the naming policy (decision D4, provisional).',
    );
  }

  const omitted = provenance.filter((record) => !record.written).length;
  if (omitted > 0) {
    lines.push(`${omitted} claim(s) omitted: no source recorded.`);
  }

  const cited = [...new Set(claims.flatMap((claim) => claim.sourceRowIds))]
    .sort()
    .slice(0, contract.bounds.maximumSourcesPerClaim);
  if (cited.length > 0) {
    lines.push('Sources:');
    for (const sourceRowId of cited) {
      const source = sourcesById.get(sourceRowId);
      if (source === undefined) continue;
      lines.push(`- ${applySubstitutions(source.publisher, contract)} — ${source.url}`);
    }
  }
  return { markdown: lines.join('\n'), provenance };
}

function header(request: DraftRequest, contract: DraftingContract): string {
  const range = `${request.periodStart} to ${request.periodEnd}`;
  const title = contract.style.titleTemplate.replace('{range}', range);
  const origin = contract.style.originLabels[request.dataOrigin] ?? request.dataOrigin;
  return [
    `# ${title}`,
    '',
    `**Status: unpublished. This draft requires human review before anything is published.**`,
    `Data origin: ${origin}. Generated deterministically from reviewed incidents; no model was`,
    `called and nothing here is AI-generated.`,
    `Period: ${request.periodStart} to ${request.periodEnd}, supplied explicitly.`,
  ].join('\n');
}

function provenanceSection(provenance: DraftProvenance): string {
  return [
    '## Provenance',
    '',
    `Draft ${provenance.draftId}, contract ${provenance.contractVersion} (${provenance.contractHash.slice(0, 12)}…).`,
    `Incidents ${provenance.counts.incidents}; claims written ${provenance.counts.claimsWritten};`,
    `claims omitted for want of a source ${provenance.counts.claimsOmitted};`,
    `names withheld ${provenance.counts.namesWithheld}; contradicted incidents ${provenance.counts.contradicted}.`,
    '',
    'Every claim above carries its incident, its sources, its evidence state and the naming',
    'decision applied to it. The machine-readable sidecar holds the same record per claim.',
  ].join('\n');
}

/** Generates one section in isolation. Used by full generation and by regeneration. */
export function generateSection(
  section: DraftSection,
  request: DraftRequest,
  contract: DraftingContract = DRAFTING_CONTRACT,
): { readonly markdown: string; readonly provenance: readonly ClaimProvenance[] } {
  const ordered = orderIncidents(request.incidents, contract).slice(
    0,
    contract.bounds.maximumIncidents,
  );
  if (section === 'header') return { markdown: header(request, contract), provenance: [] };
  if (section === 'provenance') return { markdown: '', provenance: [] };

  const wanted = ordered.filter((incident) =>
    section === 'crypto' ? incident.onChainSubject : !incident.onChainSubject,
  );
  const heading = section === 'crypto' ? '## Crypto and Web3' : '## Incidents';
  const rendered = wanted.map((incident) => renderIncident(incident, contract));
  const body =
    rendered.length === 0
      ? section === 'crypto'
        ? 'No incident in this period carries a recorded on-chain subject.'
        : 'No incident in this period.'
      : rendered.map((entry) => entry.markdown).join('\n\n');
  return {
    markdown: `${heading}\n\n${body}`,
    provenance: rendered.flatMap((entry) => [...entry.provenance]),
  };
}

/** Generates the whole draft: Markdown plus the structured provenance sidecar. */
export function generateDraft(
  request: DraftRequest,
  contract: DraftingContract = DRAFTING_CONTRACT,
): GeneratedDraft {
  const sections: Partial<Record<DraftSection, string>> = {};
  const claims: ClaimProvenance[] = [];
  for (const section of contract.sections) {
    if (section === 'provenance') continue;
    const generated = generateSection(section, request, contract);
    sections[section] = generated.markdown;
    claims.push(...generated.provenance);
  }
  const ordered = orderIncidents(request.incidents, contract).slice(
    0,
    contract.bounds.maximumIncidents,
  );
  const provenance: DraftProvenance = {
    draftId: request.draftId,
    status: 'unpublished_requires_human_review',
    draftingVersion: contract.draftingVersion,
    contractVersion: contract.contractVersion,
    contractHash: draftingContractHash(contract),
    periodStart: request.periodStart,
    periodEnd: request.periodEnd,
    dataOrigin: request.dataOrigin,
    claims,
    counts: {
      incidents: ordered.length,
      claimsWritten: claims.filter((claim) => claim.written).length,
      claimsOmitted: claims.filter((claim) => !claim.written).length,
      namesWithheld: claims.filter(
        (claim) => claim.namingDecision === 'withheld_insufficient_sourcing',
      ).length,
      contradicted: ordered.filter((incident) => incident.evidenceState === 'contradicted').length,
      cryptoIncidents: ordered.filter((incident) => incident.onChainSubject).length,
    },
  };
  sections.provenance = provenanceSection(provenance);
  const markdown = contract.sections
    .map((section) => sections[section] ?? '')
    .filter((part) => part.length > 0)
    .join('\n\n');
  return {
    markdown,
    sections: sections as Record<DraftSection, string>,
    provenance,
  };
}

/**
 * A draft identifier: lower-case letters, digits and hyphens, four to
 * sixty-four characters, starting with a letter or digit. Nothing in it can
 * name a directory, a parent, a separator or an encoded one, so it is safe to
 * become part of a path only because this allowlist says so, not because a
 * writer later tries to strip things out of it.
 */
export const DRAFT_ID_PATTERN = /^[a-z0-9][a-z0-9-]{3,63}$/u;

/** Refuses anything outside `DRAFT_ID_PATTERN` with a fixed message. */
export function assertDraftId(value: unknown): string {
  if (typeof value !== 'string' || !DRAFT_ID_PATTERN.test(value)) {
    throw new RangeError('draft identifier rejected: not a short lower-case identifier');
  }
  return value;
}

const DATE_PATTERN = /^(\d{4})-(\d{2})-(\d{2})$/u;

/**
 * The exact calendar date a period starts on, as `YYYY-MM-DD`. The period
 * start must be an ISO instant, and its date part must be a real date: the
 * thirtieth of February and the first of the thirteenth month are refused,
 * not normalized.
 */
export function publicationDate(periodStart: unknown): string {
  if (typeof periodStart !== 'string' || Number.isNaN(Date.parse(periodStart))) {
    throw new RangeError('draft period rejected: the start is not an ISO instant');
  }
  const date = periodStart.slice(0, 10);
  const match = DATE_PATTERN.exec(date);
  if (match === null || periodStart.charAt(10) !== 'T') {
    throw new RangeError('draft period rejected: the start is not an ISO calendar date and time');
  }
  const year = Number(match[1]);
  const month = Number(match[2]);
  const day = Number(match[3]);
  const utc = new Date(Date.UTC(year, month - 1, day));
  if (
    utc.getUTCFullYear() !== year ||
    utc.getUTCMonth() !== month - 1 ||
    utc.getUTCDate() !== day ||
    year < 2000 ||
    year > 2100
  ) {
    throw new RangeError('draft period rejected: the start is not a real calendar date');
  }
  return date;
}

/**
 * The directory a published draft lives in: dated, identified, and never
 * overwriting an earlier one because the identifier is part of the name
 * (decision D3, provisional). Both parts are validated here, so the name is
 * a single path component by construction.
 */
export function draftDirectoryName(request: DraftRequest): string {
  return `cyberattack-sunday-${publicationDate(request.periodStart)}-${assertDraftId(request.draftId)}`;
}

/** The Markdown file name inside a published draft directory. */
export const DRAFT_MARKDOWN_NAME = 'draft.md';
/** The provenance sidecar name beside it. */
export const DRAFT_SIDECAR_NAME = 'provenance.json';

/** The flat file name a draft carries, for callers that present one file. Validated the same way. */
export function draftFileName(request: DraftRequest): string {
  return `${draftDirectoryName(request)}.md`;
}

/** The flat sidecar name beside it. */
export function sidecarFileName(request: DraftRequest): string {
  return `${draftDirectoryName(request)}.provenance.json`;
}

/** Canonical JSON of the sidecar, stable across runs. */
export function serializeProvenance(provenance: DraftProvenance): string {
  return canonicalize(provenance);
}
