/**
 * @cas/database
 *
 * The only package that talks to PostgreSQL (docs/ARCHITECTURE.md section 2).
 * Sprint 2: connection configuration read from DATABASE_URL and never echoed,
 * a forward-only checksummed migration runner with an advisory lock, and
 * parameterized operations over the editorial ingestion tables. Sprint 3 adds
 * migration 0003 and the classification run and result operations. CSV
 * parsing, classification and calibration orchestration live in @cas/worker
 * and call these operations.
 */

export {
  assertCredentialPolicy,
  assertSchemaName,
  DATABASE_URL_VARIABLE,
  DEFAULT_APPLICATION_SCHEMA,
  MINIMUM_PASSWORD_LENGTH,
  parseDatabaseConfig,
  summarizeConnection,
  type ConnectionSummary,
  type ConnectionTransport,
  type DatabaseConfig,
} from './config.js';
export {
  completeClassificationRun,
  countBatchSourceRows,
  countReviewQueue,
  countReviewState,
  countRunDecisions,
  countRunRationaleCodes,
  countUnclassifiedRows,
  fetchCalibrationMatrix,
  fetchClassificationInputs,
  fetchReviewQueue,
  findBatchReviewSnapshot,
  freezeBatchSourceSet,
  findClassificationRunByIdempotencyKey,
  getClassificationRun,
  deriveRunDecisionCounts,
  insertClassificationResults,
  insertRunningClassificationRun,
  listClassificationRuns,
  type CalibrationMatrixCell,
  type ClassificationInputRow,
  type ClassificationRunRecord,
  type DecisionCounts,
  type NewClassificationResult,
  type NewClassificationRun,
  type QueueEntry,
  type RationaleCodeCount,
} from './classification.js';
export {
  completeClusteringRun,
  countClassificationEligibility,
  countClusteringReview,
  countClustersByKind,
  countIneligibleMemberships,
  countUncoveredEligibleResults,
  currentReviewRevision,
  deriveClusteringCounts,
  fetchClusteringInputs,
  findClusteringRunByIdempotencyKey,
  findReviewActionByIdempotencyKey,
  getClusteringRun,
  insertAmbiguousLinks,
  insertIncidentClusters,
  insertIncidentMemberships,
  insertReviewAction,
  insertRunningClusteringRun,
  listBaseMemberships,
  listReviewActions,
  type BaseMembership,
  type ClusteringCounts,
  type ClusteringInputRow,
  type ClusteringRunRecord,
  type ClusteringRunStatus,
  type NewAmbiguousLink,
  type NewClusteringRun,
  type NewIncidentCluster,
  type NewIncidentMembership,
  type NewReviewAction,
  type ReviewActionRecord,
} from './clustering.js';
export {
  CLAIM_KINDS,
  MAX_EVIDENCE_ROWS_PER_INSERT,
  completeEvidenceRun,
  completeGraphSignalRun,
  countAssociations,
  countEvidenceStates,
  countReportingWindow,
  currentEvidenceRevision,
  findEvidenceActionByIdempotencyKey,
  findEvidenceRunByIdempotencyKey,
  findGraphSignalRunByIdempotencyKey,
  findIncidentClaimByFingerprint,
  getAssociation,
  getEvidenceRun,
  getGraphSignal,
  getGraphSignalRun,
  getIncidentClaim,
  getIncidentMembership,
  getIncidentSubject,
  insertAssociations,
  insertEvidenceAction,
  insertEvidenceStates,
  insertGraphSignals,
  insertIncidentClaim,
  insertIncidentSubject,
  insertRunningEvidenceRun,
  insertRunningGraphSignalRun,
  listClusteringDecisions,
  listDraftIncidents,
  listEffectiveAssociations,
  listEvidenceActions,
  listIncidentClaims,
  listIncidentSubjects,
  listSignalHistory,
  listSignalTargets,
  listSignalsForRun,
  type AssociationRecord,
  type EvidenceActionRecord,
  type EvidenceRunRecord,
  type ClaimKind,
  type EvidenceStateCounts,
  type GraphSignalRecord,
  type GraphSignalRunRecord,
  type IncidentClaimRecord,
  type IncidentMembershipRecord,
  type IncidentSubjectRecord,
  type NewAssociation,
  type NewEvidenceAction,
  type NewEvidenceRun,
  type NewEvidenceState,
  type NewGraphSignal,
  type NewGraphSignalRun,
  type NewIncidentClaim,
  type NewIncidentSubject,
} from './evidence.js';
export {
  countDashboardTotals,
  findReviewQueueEntry,
  getIncidentCluster,
  listAssociationDetails,
  listClusteringRuns,
  listEvidenceRuns,
  listGraphSignalRuns,
  listIncidentClusters,
  listIncidentEvidenceStates,
  listIncidentMembers,
  listReviewQueueEntries,
  type AssociationDetail,
  type ClusteringRunSummary,
  type DashboardTotals,
  type EvidenceRunSummary,
  type GraphSignalRunSummary,
  type IncidentClusterSummary,
  type IncidentEvidenceStateSummary,
  type IncidentMemberSummary,
  type ReviewQueueEntry,
} from './dashboard.js';
export {
  Database,
  openDatabase,
  type DatabaseOptions,
  type IsolationLevel,
  type Queryable,
  type TransactionOptions,
} from './database.js';
export {
  appendAuditEvent,
  appendDraftRevision,
  appendQueueDecision,
  bumpThrottleBucket,
  clearThrottleBucket,
  findAccountByUsername,
  findSessionByTokenHash,
  getAccountById,
  getThrottleBucket,
  insertAccount,
  insertSession,
  latestDraftRevision,
  listAccounts,
  listAuditEvents,
  listDraftRevisions,
  listQueueDecisionsForRun,
  listSessionsForAccount,
  revokeAllSessionsForAccount,
  revokeSession,
  setAccountDisabled,
  setAccountExpiresAt,
  setAccountPasswordHash,
  setAccountRole,
  touchSession,
  type AccountRow,
  type AuditEventRow,
  type DraftRevisionRow,
  type QueueDecisionRow,
  type SessionRow,
  type ThrottleBucket,
} from './dashboard-auth.js';
export {
  classifyDriverError,
  DATABASE_CODE_SOURCES,
  DATABASE_FAILURE_KINDS,
  DatabaseError,
  isDatabaseError,
  type DatabaseCodeSource,
  type DatabaseFailureKind,
  type SafeDetailValue,
} from './errors.js';
export {
  countAllRows,
  countRowIssues,
  countSourceRows,
  ensureUrlGroups,
  finalizeImportBatch,
  findImportBatchByIdempotencyKey,
  getImportBatch,
  getSourceRows,
  insertImportBatch,
  insertReviewEntries,
  insertReviewSnapshot,
  insertRowIssues,
  insertSourceRows,
  listImportBatches,
  MAX_ROWS_PER_INSERT,
  summarizeReviewSnapshot,
  summarizeUrlGroups,
  type BatchCompletion,
  type ImportBatchRecord,
  type IssueCodeCount,
  type NewImportBatch,
  type NewReviewEntry,
  type NewReviewSnapshot,
  type NewRowIssue,
  type NewSourceRow,
  type ReviewSnapshotSummary,
  type ReviewStateCount,
  type SourceRowCounts,
  type StoredSourceRow,
  type UrlGroupStats,
} from './ingestion.js';
export {
  loadMigrations,
  MIGRATIONS_DIRECTORY,
  migrationStatus,
  runMigrations,
  type AppliedMigration,
  type MigrationDrift,
  type MigrationFile,
  type MigrationRunResult,
  type MigrationStatus,
} from './migrate.js';
export { connectionSecrets, createRedactor, REDACTED, type Redactor } from './redact.js';
export { createSchema, dropSchema, listTables, quoteIdentifier } from './schema.js';
